redis:
  host: "localhost"
  port: 6379
  auth:
    enabled: false
    password: "none"

messages:
  queue-position: "&7You are in position &a%pos%&8/&a%total% &7in the queue for %server%&7."
  queue-paused: "&7The queue for %server% &7is currently paused."
